In [13]:
import json
import pandas as pd

# ../../data/tmap_puzzle_get-off.json 읽기
with open('../raw/tmap_puzzle_get-off.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [14]:
'''
df를 DataFrame으로 변환

DataFrame의 각 열은 다음과 같음:
- subwayLine : api_response의 contents의 subwayLine 값
- stationName: api_response의 contents의 stationName 값
- stationCode: api_response의 contents의 stationCode 값
- updnLine : api_response의 contents의 stat의 updnLine 값
- dow: api_response의 contents의 stat의 i번째의 data의 dow 값
- hh : api_response의 contents의 stat의 i번째의 data의 hh 값
- mm : api_response의 contents의 stat의 i번째의 data의 mm 값
- getOffCarRate : api_response의 contents의 stat의 i번째의 data의 getOffCarRate 값
- prevStationName : api_response의 contents의 stat의 prevStationName 값
- prevStationCode : api_response의 contents의 stat의 prevStationCode 값
- startStationName : api_response의 contents의 stat의 startStationName 값
- startStationCode : api_response의 contents의 stat의 startStationCode 값
- endStationName : api_response의 contents의 stat의 endStationName 값
- endStationCode : api_response의 contents의 stat의 endStationCode 값
- statStartDate : api_response의 contents의 statStartDate 값
- statEndDate : api_response의 contents의 statEndDate 값
'''


records = []

for entry in data:
    contents = entry['api_response']['contents']
    subway_line = contents['subwayLine']
    station_name = contents['stationName']
    station_code = contents['stationCode']
    stat_start_date = contents['statStartDate']
    stat_end_date = contents['statEndDate']
    
    for stat in contents['stat']:
        updn_line = stat['updnLine']
        prev_station_code = stat['prevStationCode']
        prev_station_name = stat['prevStationName']
        start_station_code = stat['startStationCode']
        start_station_name = stat['startStationName']
        end_station_code = stat['endStationCode']
        end_station_name = stat['endStationName']
        
        for data_point in stat['data']:
            record = {
                'subwayLine': subway_line,
                'stationName': station_name,
                'stationCode': station_code,
                'updnLine': updn_line,
                'dow': data_point['dow'],
                'hh': data_point['hh'],
                'mm': data_point['mm'],
                'getOffCarRate': data_point['getOffCarRate'],
                'prevStationName': prev_station_name,
                'prevStationCode': prev_station_code,
                'startStationName': start_station_name,
                'startStationCode': start_station_code,
                'endStationName': end_station_name,
                'endStationCode': end_station_code,
                'statStartDate': stat_start_date,
                'statEndDate': stat_end_date
            }
            records.append(record)
df = pd.DataFrame.from_records(records)

In [15]:
# df csv로 저장
df.to_csv('../../data/tmap_puzzle_raw_get-off.csv', index=False, encoding='utf-8-sig')
df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,getOffCarRate,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
0,2호선,교대역,223,0,MON,17,00,"[4, 5, 6, 8, 10, 11, 10, 9, 14, 24]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
1,2호선,교대역,223,0,MON,17,10,"[4, 6, 6, 8, 10, 10, 11, 9, 14, 24]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
2,2호선,교대역,223,0,MON,17,20,"[4, 5, 7, 8, 10, 9, 11, 8, 14, 24]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
3,2호선,교대역,223,0,MON,17,30,"[4, 5, 8, 7, 9, 9, 11, 9, 14, 22]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
4,2호선,교대역,223,0,MON,17,40,"[4, 5, 8, 7, 10, 10, 11, 9, 14, 23]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39703,6호선,신당역,635,1,SUN,19,10,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201
39704,6호선,신당역,635,1,SUN,19,20,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201
39705,6호선,신당역,635,1,SUN,19,30,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201
39706,6호선,신당역,635,1,SUN,19,40,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201
39707,6호선,신당역,635,1,SUN,19,50,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201

In [16]:
'''
stationCode=222, updnline=1, dow=MON, hh=18, mm=00 필터링
'''
filtered_df = df[
    (df['subwayLine'] == '2호선') &
    # (df['stationCode'] == '222') &
    (df['updnLine'] == 1) &
    (df['startStationName'] == '삼성역')
    # (df['dow'] == 'MON') &
    # (df['hh'] == '18') &
    # (df['mm'] == '00')
]
filtered_df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,getOffCarRate,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
12,2호선,교대역,223,1,MON,17,00,"[24, 14, 10, 12, 8, 8, 8, 7, 5, 3]",강남역,222,삼성역,219,성수역,211-R,20251102,20260201
13,2호선,교대역,223,1,MON,17,10,"[25, 13, 10, 12, 8, 8, 7, 7, 6, 3]",강남역,222,삼성역,219,성수역,211-R,20251102,20260201
14,2호선,교대역,223,1,MON,17,20,"[25, 13, 11, 12, 8, 7, 7, 8, 5, 3]",강남역,222,삼성역,219,성수역,211-R,20251102,20260201
15,2호선,교대역,223,1,MON,17,30,"[25, 13, 11, 12, 9, 7, 8, 7, 5, 4]",강남역,222,삼성역,219,성수역,211-R,20251102,20260201
16,2호선,교대역,223,1,MON,17,40,"[24, 13, 12, 12, 8, 7, 8, 7, 5, 4]",강남역,222,삼성역,219,성수역,211-R,20251102,20260201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9457,2호선,선릉역,220,1,SUN,19,10,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251102,20260201
9458,2호선,선릉역,220,1,SUN,19,20,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251102,20260201
9459,2호선,선릉역,220,1,SUN,19,30,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251102,20260201
9460,2호선,선릉역,220,1,SUN,19,40,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251102,20260201
9461,2호선,선릉역,220,1,SUN,19,50,"[5, 9, 11, 12, 14, 15, 12, 9, 8, 5]",삼성역,219,삼성역,219,성수역,211-R,20251102,20260201

In [17]:
'''
df에서 df['subwayLine'] == '2호선'일때, (df['updnLine'] == 1) & (df['endStationName'] != '서울대입구역')만 남기기
df에서 df['subwayLine'] == '7호선'일때, (df['updnLine'] == 1) & ((df['endStationName'] != '신풍역')| (df['startStationName'] != '신풍역'))만 남기기
'''
# scenario_df = df[(df['updnLine'] == 1)]
scenario_df = df[
    ~(
        ((df['subwayLine'] == '2호선') & (df['updnLine'] == 1) & ((df['endStationName'] == '서울대입구역') | (df['startStationName'] == '삼성역') | (df['endStationName'] == '삼성역'))) |
        ((df['subwayLine'] == '7호선') & (df['updnLine'] == 1) & ((df['endStationName'] == '신풍역') | (df['startStationName'] == '신풍역')))
    )
]
scenario_df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,getOffCarRate,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
0,2호선,교대역,223,0,MON,17,00,"[4, 5, 6, 8, 10, 11, 10, 9, 14, 24]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
1,2호선,교대역,223,0,MON,17,10,"[4, 6, 6, 8, 10, 10, 11, 9, 14, 24]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
2,2호선,교대역,223,0,MON,17,20,"[4, 5, 7, 8, 10, 9, 11, 8, 14, 24]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
3,2호선,교대역,223,0,MON,17,30,"[4, 5, 8, 7, 9, 9, 11, 9, 14, 22]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
4,2호선,교대역,223,0,MON,17,40,"[4, 5, 8, 7, 10, 10, 11, 9, 14, 23]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39703,6호선,신당역,635,1,SUN,19,10,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201
39704,6호선,신당역,635,1,SUN,19,20,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201
39705,6호선,신당역,635,1,SUN,19,30,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201
39706,6호선,신당역,635,1,SUN,19,40,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201
39707,6호선,신당역,635,1,SUN,19,50,"[8, 13, 18, 12, 9, 9, 14, 18]",청구역,634,한강진역,631,신내역,648,20251102,20260201

In [18]:
scenario_df.to_csv('../../data/tmap_puzzle_filtering_get-off.csv', index=False, encoding='utf-8-sig')