In [27]:
import json
import pandas as pd

# ../../data/tmap_puzzle_car.json 읽기
with open('../raw/tmap_puzzle_car.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [28]:
'''
df를 DataFrame으로 변환

DataFrame의 각 열은 다음과 같음:
- subwayLine : api_response의 contents의 subwayLine 값
- stationName: api_response의 contents의 stationName 값
- stationCode: api_response의 contents의 stationCode 값
- updnLine : api_response의 contents의 stat의 updnLine 값
- dow: api_response의 contents의 stat의 i번째의 data의 dow 값
- hh : api_response의 contents의 stat의 i번째의 data의 hh 값
- mm : api_response의 contents의 stat의 i번째의 data의 mm 값
- congestionCar : api_response의 contents의 stat의 i번째의 data의 congestionCar 값
- prevStationName : api_response의 contents의 stat의 prevStationName 값
- prevStationCode : api_response의 contents의 stat의 prevStationCode 값
- startStationName : api_response의 contents의 stat의 startStationName 값
- startStationCode : api_response의 contents의 stat의 startStationCode 값
- endStationName : api_response의 contents의 stat의 endStationName 값
- endStationCode : api_response의 contents의 stat의 endStationCode 값
- statStartDate : api_response의 contents의 statStartDate 값
- statEndDate : api_response의 contents의 statEndDate 값
'''


records = []

for entry in data:
    contents = entry['api_response']['contents']
    subway_line = contents['subwayLine']
    station_name = contents['stationName']
    station_code = contents['stationCode']
    stat_start_date = contents['statStartDate']
    stat_end_date = contents['statEndDate']
    
    for stat in contents['stat']:
        updn_line = stat['updnLine']
        prev_station_code = stat['prevStationCode']
        prev_station_name = stat['prevStationName']
        start_station_code = stat['startStationCode']
        start_station_name = stat['startStationName']
        end_station_code = stat['endStationCode']
        end_station_name = stat['endStationName']
        
        for data_point in stat['data']:
            record = {
                'subwayLine': subway_line,
                'stationName': station_name,
                'stationCode': station_code,
                'updnLine': updn_line,
                'dow': data_point['dow'],
                'hh': data_point['hh'],
                'mm': data_point['mm'],
                'congestionCar': data_point['congestionCar'],
                'prevStationName': prev_station_name,
                'prevStationCode': prev_station_code,
                'startStationName': start_station_name,
                'startStationCode': start_station_code,
                'endStationName': end_station_name,
                'endStationCode': end_station_code,
                'statStartDate': stat_start_date,
                'statEndDate': stat_end_date
            }
            records.append(record)
df = pd.DataFrame.from_records(records)

In [29]:
# df csv로 저장
df.to_csv('../../data/tmap_puzzle_raw_car.csv', index=False, encoding='utf-8-sig')
df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,congestionCar,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
0,2호선,교대역,223,0,MON,17,00,"[17, 20, 19, 28, 26, 25, 25, 18, 18, 15]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
1,2호선,교대역,223,0,MON,17,10,"[38, 39, 47, 49, 55, 47, 48, 40, 33, 34]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
2,2호선,교대역,223,0,MON,17,20,"[28, 34, 32, 41, 47, 37, 37, 35, 29, 29]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
3,2호선,교대역,223,0,MON,17,30,"[50, 62, 56, 93, 76, 73, 74, 57, 47, 51]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
4,2호선,교대역,223,0,MON,17,40,"[59, 65, 78, 85, 98, 81, 66, 61, 52, 54]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39703,6호선,신당역,635,1,SUN,19,10,"[27, 30, 35, 27, 15, 24, 14, 20]",청구역,634,공덕역,626,신내역,648,20251102,20260201
39704,6호선,신당역,635,1,SUN,19,20,"[18, 45, 46, 31, 28, 20, 12, 9]",청구역,634,공덕역,626,신내역,648,20251102,20260201
39705,6호선,신당역,635,1,SUN,19,30,"[24, 26, 31, 35, 30, 12, 19, 23]",청구역,634,공덕역,626,신내역,648,20251102,20260201
39706,6호선,신당역,635,1,SUN,19,40,"[34, 32, 24, 24, 25, 23, 16, 7]",청구역,634,공덕역,626,신내역,648,20251102,20260201
39707,6호선,신당역,635,1,SUN,19,50,"[33, 30, 31, 32, 18, 16, 22, 11]",청구역,634,공덕역,626,신내역,648,20251102,20260201

In [30]:
'''
stationCode=222, updnline=1, dow=MON, hh=18, mm=00 필터링
'''
filtered_df = df[
    (df['subwayLine'] == '7호선') &
    # (df['stationCode'] == '222') &
    (df['updnLine'] == 1) &
    ((df['endStationName'] == '신풍역')| 
    (df['startStationName'] == '신풍역'))
    # (df['dow'] == 'MON') &
    # (df['hh'] == '18') &
    # (df['mm'] == '00')
]
filtered_df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,congestionCar,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
11904,7호선,대림역,744,1,MON,17,00,"[51, 42, 49, 48, 47, 49, 39, 35]",신풍역,743,신풍역,743,석남역,761,20251102,20260201
11905,7호선,대림역,744,1,MON,17,10,"[50, 56, 50, 50, 53, 49, 48, 35]",신풍역,743,신풍역,743,석남역,761,20251102,20260201
11906,7호선,대림역,744,1,MON,17,20,"[51, 52, 40, 46, 50, 50, 47, 41]",신풍역,743,신풍역,743,석남역,761,20251102,20260201
11907,7호선,대림역,744,1,MON,17,30,"[75, 78, 74, 70, 76, 70, 77, 56]",신풍역,743,신풍역,743,석남역,761,20251102,20260201
11908,7호선,대림역,744,1,MON,17,40,"[72, 78, 74, 72, 79, 86, 67, 63]",신풍역,743,신풍역,743,석남역,761,20251102,20260201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23149,7호선,광명사거리역,748,1,SUN,19,10,"[23, 34, 30, 29, 27, 29, 25, 19]",철산역,747,신풍역,743,석남역,761,20251102,20260201
23150,7호선,광명사거리역,748,1,SUN,19,20,"[29, 33, 31, 28, 35, 31, 21, 17]",철산역,747,신풍역,743,석남역,761,20251102,20260201
23151,7호선,광명사거리역,748,1,SUN,19,30,"[30, 27, 28, 23, 30, 31, 23, 16]",철산역,747,신풍역,743,석남역,761,20251102,20260201
23152,7호선,광명사거리역,748,1,SUN,19,40,"[26, 16, 24, 15, 13, 18, 13, 10]",철산역,747,신풍역,743,석남역,761,20251102,20260201
23153,7호선,광명사거리역,748,1,SUN,19,50,"[24, 20, 25, 29, 28, 27, 22, 17]",철산역,747,신풍역,743,석남역,761,20251102,20260201

In [31]:
'''
df에서 df['subwayLine'] == '2호선'일때, (df['updnLine'] == 1) & (df['endStationName'] != '서울대입구역')만 남기기
df에서 df['subwayLine'] == '7호선'일때, (df['updnLine'] == 1) & ((df['endStationName'] != '신풍역')| (df['startStationName'] != '신풍역'))만 남기기
'''
# scenario_df = df[(df['updnLine'] == 1)]
scenario_df = df[
    ~(
        ((df['subwayLine'] == '2호선') & (df['updnLine'] == 1) & ((df['endStationName'] == '서울대입구역') | (df['startStationName'] == '삼성역') | (df['endStationName'] == '삼성역'))) |
        ((df['subwayLine'] == '7호선') & (df['updnLine'] == 1) & ((df['endStationName'] == '신풍역') | (df['startStationName'] == '신풍역')))
    )
]
scenario_df

,subwayLine,stationName,stationCode,updnLine,dow,hh,mm,congestionCar,prevStationName,prevStationCode,startStationName,startStationCode,endStationName,endStationCode,statStartDate,statEndDate
0,2호선,교대역,223,0,MON,17,00,"[17, 20, 19, 28, 26, 25, 25, 18, 18, 15]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
1,2호선,교대역,223,0,MON,17,10,"[38, 39, 47, 49, 55, 47, 48, 40, 33, 34]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
2,2호선,교대역,223,0,MON,17,20,"[28, 34, 32, 41, 47, 37, 37, 35, 29, 29]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
3,2호선,교대역,223,0,MON,17,30,"[50, 62, 56, 93, 76, 73, 74, 57, 47, 51]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
4,2호선,교대역,223,0,MON,17,40,"[59, 65, 78, 85, 98, 81, 66, 61, 52, 54]",서초역,224,뚝섬역,210,성수역,211-R,20251102,20260201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39703,6호선,신당역,635,1,SUN,19,10,"[27, 30, 35, 27, 15, 24, 14, 20]",청구역,634,공덕역,626,신내역,648,20251102,20260201
39704,6호선,신당역,635,1,SUN,19,20,"[18, 45, 46, 31, 28, 20, 12, 9]",청구역,634,공덕역,626,신내역,648,20251102,20260201
39705,6호선,신당역,635,1,SUN,19,30,"[24, 26, 31, 35, 30, 12, 19, 23]",청구역,634,공덕역,626,신내역,648,20251102,20260201
39706,6호선,신당역,635,1,SUN,19,40,"[34, 32, 24, 24, 25, 23, 16, 7]",청구역,634,공덕역,626,신내역,648,20251102,20260201
39707,6호선,신당역,635,1,SUN,19,50,"[33, 30, 31, 32, 18, 16, 22, 11]",청구역,634,공덕역,626,신내역,648,20251102,20260201

In [32]:
scenario_df.to_csv('../../data/tmap_puzzle_filtering_car.csv', index=False, encoding='utf-8-sig')